# fly.toml app configuration file generated for remix-vite-template on 2023-12-04T17:18:57-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "remix-vite-template"
primary_region = "iad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/resources/healthcheck"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
